Wr/oss cli
salesforcecli/sfdx-cli pull request #3
Opened 2021-01-19 20:48 UTC by WillieRuemmele

### What does this PR do?
Open Sources the sfdx-cli repository
### What issues does this PR fix or reference?
@W-8222430@

2021-01-19 21:54 UTC, shetzel commented
@WillieRuemmele - you don't want to source control `./dist` right?

2021-01-19 21:59 UTC, WillieRuemmele commented
> @WillieRuemmele - you don't want to source control `./dist` right?

@shetzel I don't believe it is... I don't think it should be

2021-01-20 00:04 UTC, shetzel approved these changes
That's weird.  First time I looked I saw the dist dir and compiled files.  I don't see them anymore so lgtm.

2021-01-21 05:36 UTC, amphro requested changes

2021-01-21 05:36 UTC, amphro commented on src/updateReachability.test.ts
> +    env.setS3HostOverride('http://10.252.156.165:9000/sfdx/media/salesforce-cli');
IP needs to be changed. We also need to remove this message about SFM.

2021-01-21 18:16 UTC, amphro approved these changes

2021-01-21 18:17 UTC, merged