chore: revert promote-to-latest cron
salesforcecli/sfdx-cli pull request #515
Opened 2022-03-11 23:08 UTC by cristiand391

### What does this PR do?

Reverts promote-to-latest cron back to `00 16 * * 4`

2022-03-11 23:08 UTC, WillieRuemmele approved these changes

2022-03-14 14:12 UTC, RodEsp requested changes

2022-03-14 14:15 UTC, RodEsp commented on .circleci/config.yml
> +          cron: '00 16 * * 4'
Oh, never mind. The comment wasn't switched originally so now that it's being switched back it matches again.

2022-03-14 14:15 UTC, RodEsp approved these changes

2022-03-16 16:54 UTC, merged